MODEL:
    ARCHITECTURE: unet
    BACKBONE: 'timm-efficientnet-b3'
DATALOADER:
    TRAIN_BATCH_SIZE: 12
    VAL_BATCH_SIZE: 4
    TEST_BATCH_SIZE: 4
    TRAIN_NUM_WORKERS: 8
    VAL_NUM_WORKERS: 8
    TEST_NUM_WORKERS: 8
TRANSFORM:
    SIZE_SCALE: 2.0
