MODEL:
    ARCHITECTURE: unet
    BACKBONE: 'timm-efficientnet-b3'
    UNET_ENABLE_DECODER_SCSE: True
DATALOADER:
    TRAIN_BATCH_SIZE: 16
    VAL_BATCH_SIZE: 12
    TEST_BATCH_SIZE: 12
    TRAIN_NUM_WORKERS: 8
    VAL_NUM_WORKERS: 8
    TEST_NUM_WORKERS: 8