MODEL:
    ARCHITECTURE: unet
    BACKBONE: 'timm-efficientnet-b0'
DATALOADER:
    TRAIN_BATCH_SIZE: 8
    VAL_BATCH_SIZE: 1
    TEST_BATCH_SIZE: 1
    TRAIN_NUM_WORKERS: 8
    VAL_NUM_WORKERS: 8
    TEST_NUM_WORKERS: 8
TRANSFORM:
    SIZE_SCALE: 4.0
    TRAIN_RANDOM_CROP_SIZE: (160, 160)
