MODEL:
    ARCHITECTURE: unet
    BACKBONE: 'timm-efficientnet-b5'
DATALOADER:
    TRAIN_BATCH_SIZE: 16
    VAL_BATCH_SIZE: 16
    TEST_BATCH_SIZE: 16
    TRAIN_NUM_WORKERS: 8
    VAL_NUM_WORKERS: 8
    TEST_NUM_WORKERS: 8